# Base configs
# For a Vercel deployment, keep this empty so the site works on preview and custom domains.
baseurl: ""
url: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Bogdan Zogovic"
subtitle: "See the world through my eyes!"
author: "Bogdan Zogovic"
header:
 title: "Photography"
 subtitle: "by Bogdan Zogovic"
footer:
 name: "Hey there, my name is Bogdan"
 bio: "I am a photographer and software developer"
 github: ""

social_urls:
  tiktok: "https://www.tiktok.com/@photography.bz"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'